# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        app_user_provider:
            entity:
                class: CM\UserBundle\Entity\User
                property: username
    password_hashers:
        CM\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5000
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            lazy: true
            form_login:
                provider: app_user_provider
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                enable_csrf: true
                always_use_default_target_path: false
                default_target_path:            /cm/game/start
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login

    access_control:
        - { path: ^/cm/game, roles: ROLE_USER, requires_channel: http }
        - { path: ^/cm/login, roles: PUBLIC_ACCESS, requires_channel: http }
